### ISSUE TITLE
Iconography 16 Bit

### ISSUE THREAD

**Issue by SpicySoju2k20** [Latent-Arcana/project-dungeon#65]
- [x] heart
- [x] book
- [x] exit / escape / 'x'
- [x] bag / inventory
- [x] warning
- [x] enemy close by
- [x] inventory / 'i'
- [x] map / 'm'
- [x] compass

**Comment by LatentArchitect** [comment]
# Feedback on current iterations @yooaudrey 

### heart
need some differentiation in values/color to match the others
![Image](https://github.com/user-attachments/assets/5c839239-f190-4e04-9ef9-270da37874e1)

### book
i would literally just change the bookmark color a bit in value to separate it visually from the white and remove the light 'lavendar' ish color. just a bit too much depth with all three purples there
![Image](https://github.com/user-attachments/assets/a36e1092-27f2-472e-95dc-ff244e346dcb)

### exit
i would make an icon for it rather than the text. like this https://t4.ftcdn.net/jpg/00/66/46/87/360_F_66468754_86IFi1dhqwtHdXzPeMQNhGtGp8Z2D3yC.jpg
![Image](https://github.com/user-attachments/assets/519d72ab-abe3-47e0-97b7-e75db0d938f6)

### bag (both open an closed)
pretty much perfect
![Image](https://github.com/user-attachments/assets/dfad82d1-3c46-4871-8253-a6fef717d10e)
![Image](https://github.com/user-attachments/assets/66850ed2-44c7-4d95-b24a-81c67920bd3a)

### warning
pretty much perfect
![Image](https://github.com/user-attachments/assets/f67bb82c-07b6-4abe-a628-ecef67d08df2)

### enemy close by
i like the arrows on the side, i would make the bottom of the questikon mark alligned toward the center of the rest of it
![Image](https://github.com/user-attachments/assets/e60bfb16-2fed-4c8d-a66a-6f13dcd7c874)

**Comment by LatentArchitect** [comment]
All good
