### ISSUE TITLE
16-Bit Assets (Audrey)

### ISSUE THREAD

**Issue by SpicySoju2k20** [Latent-Arcana/project-dungeon#75]
Update the following items to 16-Bit:

- General Armor:

- [x] Gambeson Robes
- [x] Elk's Hide Armor
- [x] Hauberk
- [x] Plackart
- [x] Laminar Plate Mail

- General Weapons:

- [x] Saber
- [x] Battle Axe
- [x] Heavy Mace
- [x] Halberd
- [x] Falchion

- Consumables:

- [x] Elixir of Health
- [x] Vial of Pure Strength
- [x] Vial of Pure Speed
- [x] Vial of Pure Adrenaline
- [x] Vial of Pure Stamina

- Misc. :

- [x] Pile of Glass / Spikes

**Comment by LatentArchitect** [comment]
# MY NOTES for @yooaudrey 

## ADJUSTMENTS 2024-10-10

### glass-pile.ase
implying some separate pieces of glass would help show what the material is
other than that good

### potion-stamina.ase
make the outline a color that is chromatically similar in some way to the internal liquid (like another yellow or red)
just cant remember the right term for that in color theory

### potion-adrenaline.ase
same as stamina but with this color rather than yellow

### potion-speed.ase
same as stamina but with this color rather than yellow

### potion-strength.ase
same as stamina but with this color rather than yellow

### gambeson_robe.ase
i would make it a little less geometric on the left side. like just bit more of an organic shape
like toward the skirt bit on the left

### hauberk 1.ase
looks great

### laminar-plate.ase
i would make the shape just a bit closer to that of a stereotypical torso. wider on the top and a little thinner toward the waist.
you could this be through the shoulder plates, as well, by having some sort of implication of a curve or angle downward.
making it just a tad taller and a tad wider at the chest might help if you run out of space or feel like you don't have enough room.

### mace.ase
adding a bit more stock and fullness would help on this one.
one thing that can help with this is tilting the object in frame or even cutting some of the object out of the frame so that the focal point has more room for detail
this can show that the object is a mace without showing the _whole_ thing. like only showing the head.

### FIN_halberd.ase
move staff line up by one pixel and pretty much set otherwise
